dataset:
  input_size: 96
  batch_size: 64
  num_workers: 4
  dataset: blocks
training:
  lr: 0.0005779322403055052
  weight_decay: 0.0000003215826495926
  training: 0.6
  validation: 0.2
model:
  layers: [8, 16, 32, 64]
  movements_layers: [16]
  out_channels: 1
  input_channels: 1
  actions: 48
  block: residual
  log: True
