# Dataset configuration
input_size: 96
batch_size: 64
num_workers: 4
# Training configuration
lr: 0.0005779322403055052
weight_decay: 0.0000003215826495926
num_movement: 4
# Start model configuration
layers: [8, 16, 32, 64]
movements_layers: [16]
out_channels: 1
input_channels: 1
movements: 4
block: residual
log: True
