# Dataset configuration
input_size: 160
batch_size: 64
num_workers: 4
dataset: lights-out
# Training configuration
lr: 0.0005779322403055052
weight_decay: 0.0000003215826495926
num_movement: 25
# Start model configuration
layers: [8, 16, 32, 64]
movements_layers: [16]
out_channels: 1
input_channels: 1
movements: 25
block: residual
log: True
