ORDERED_ORDER = tuple(range(9))

LEFT_RIGHT_MOVEMENTS = [1, -1]
TOP_BOT_MOVEMENTS = [3, -3]
MOVEMENTS = [*LEFT_RIGHT_MOVEMENTS, *TOP_BOT_MOVEMENTS]

MOVEMENT_TO_LABEL = {1: 0, -1: 1, 3: 2, -3: 3}
LABEL_TO_MOVEMENT = {value: key for key, value in MOVEMENT_TO_LABEL.items()}
